### PR TITLE
Remove unnecessary request-body

### PR DESCRIPTION
**Pull request by eureseb**
Removed request_body-NoneSerializer in controller GET method.

### CODE REVIEW

**Comment by slaee** [comment]
image

naa pa diay ni eurese

**Comment by eureseb** [comment]
Ah, so dili sa GET requests lang? Diba pwede ra request_body sa PUT, POST, DELETE, PATCH.
image

I think nag gamit pud mo ug same
image

**Comment by slaee** [comment]
@eureseb ang issue naa sa my_pitch function, kay get iyang request method nya naay request_body.

**Comment by eureseb** [comment]
I see. Mali yung yung description ko pala dapat GET hindi POST. Change made.

**Review by slaee — APPROVED** [review]
Goods

**Pull request merged**
